# Generated by Django 2.0.1 on 2021-02-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.PositiveIntegerField(verbose_name='主机IP'),
        ),
    ]
