# Generated by Django 2.0.1 on 2021-02-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapp', '0002_auto_20210223_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='主机IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.PositiveIntegerField(default=22, verbose_name='端口'),
        ),
    ]
